version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oauth2_user_api
    # Add platform run on MAC M1 apple silicon
    platform: linux/amd64
    ports:
      - 9090:9090
    env_file:
      - ./env/test.env
    depends_on:
      - "mysql"
      - "redis"
    volumes:
      - ./config.json:/app/config.json
      - ./env:/app/env/
      - /var/log/oauth2-server:/app/logs
    environment: 
      WAIT_HOSTS: mysql:${MYSQL_PORT}, redis:${REDIS_PORT}
  ###=================================================###
  mysql:
    image: mysql:5.7
    # Add platform run on MAC M1 apple silicon
    platform: linux/amd64
    container_name: go_oauth2_mysql
    env_file:
      - ./env/test.env
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /var/mysql_oauth2_srv:/var/lib/mysql
      - ./db_oauth2.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  ###=================================================###
  redis:
    image: bitnami/redis:latest
    container_name: go_oauth2_redis
    env_file:
      - ./env/test.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - /var/redis_oauth2_srv:/bitnami/redis/data
